apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rdwbb5i3e-nodejs 
  janus-idp.io/tekton: rdwbb5i3e-nodejs
  backstage.io/kubernetes-id: rdwbb5i3e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rdwbb5i3e-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml