apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rdwbb5i3e-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rdwbb5i3e-nodejs 
  name: rdwbb5i3e-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rdwbb5i3e-nodejs 
